name: tryanderror
on:
  push:

jobs:
  testrun:
    runs-on: ubuntu-latest
    container: rootproject/root-ubuntu16
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          repository: pseyfert/tmva-branch-adder
      - name: configure
        uses: nicledomaS/cmake_build_action@v1
        with:
          cmake_args: -DCMAKE_EXPORT_COMPILE_COMMANDS=YES;
      - name: extractor test
        uses: pseyfert/extractor_action@master
        with:
          exe: "echo"
          build_path: "build"

