name: tryanderror
on:
  push:

jobs:
  testrun:
    runs-on: ubuntu-latest
    container: rootproject/root-ubuntu16
    steps:
      - name: bodge permissions and install build dependencies
        run: |
          sudo mkdir -p /__w
          sudo chmod -R 777 /__w
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y ninja-build
      - name: checkout
        uses: actions/checkout@master
        with:
          repository: pseyfert/tmva-branch-adder
      - name: configure
        uses: nicledomaS/cmake_build_action@v1
        with:
          cmake_args: -DCMAKE_EXPORT_COMPILE_COMMANDS=YES;-GNinja;-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      - name: dump
        run: |
          echo "pwd:"
          pwd
          echo "readlink -f \$(pwd):"
          readlink -f $(pwd)
          echo "ls -l"
          ls -l
          echo "ls -l build"
          ls -l build
          echo "readlink -f build/compile_commands.json"
          readlink -f build/compile_commands.json
          echo "cat build/compile_commands.json"
          cat build/compile_commands.json
      - name: extractor test (preprocess everything rather than compiling)
        uses: pseyfert/extractor_action@master
        with:
          build_path: ./build/compile_commands.json
          replace_args: ^-c$=-E
      - name: check preprocessing output
        run: |
          cat build/CMakeFiles/tmva-branch-adder.dir/src/blacklist.cpp.o

